### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by BabakHemmatian** [BabakHemmatian/Gay_Marriage_Corpus_Study#1]
Hi Sabina,

Since I couldn't get gensim to run on my Windows, I decided to go with the lda package. It requires a document-term cooccurrence matrix as input and I spent all day today writing code to create that matrix. While it worked on a toy body of text I created, the computer apparently runs out of memory before creating such a matrix for two files from the corpus. Do you know how I can get around this issue? I added the code to the parsereddit file. I have also added the lda code (copied from the package, might need changes) as a comment at the end of the code.

Thanks!

**Comment by sabjoslo** [comment]
Sure, I'll take a look. In the meantime, could you copy and paste the traceback (the exact error you're getting and the line number it's failing on) here?

**Comment by BabakHemmatian** [comment]
Thank you! I'll run the code again in the morning before our meeting and send you the traceback.

Babak

**Comment by BabakHemmatian** [comment]
Traceback (most recent call last):
  File "parsereddit", line 62, in <module>
    cooc_mat = np.c_[cooc_mat,np.zeros((len(cooc_mat),1))]
  File "C:\Python27\lib\site-packages\numpy\lib\index_tricks.py", line 340, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
MemoryError

**Comment by sabjoslo** [comment]
@BabakHemmatian, has this been addressed?

**Comment by BabakHemmatian** [comment]
Yeah. I ran the code on all the comments from 2005-6 and didn't get any error
