### ISSUE TITLE
Add arg to select_random_comments to only select from comments with length > min_comm_length

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#14]
See title.

**Comment by BabakHemmatian** [comment]
There's another issue with the random subsample. To calculate topic contribution properly, we need a list of how many instances come from each year and that's not very clear for the first few years when we're sampling randomly. If you could add an output to your sampling function that includes those counts, I could finish up the analysis and write to all collaborators with the results. Thanks!

**Comment by sabjoslo** [comment]
@BabakHemmatian, see ecbc10f.
