### ISSUE TITLE
Rating predictors

### ISSUE THREAD

**Issue by BabakHemmatian** [BabakHemmatian/Gay_Marriage_Corpus_Study#17]
Which topics predict the value vs. consequence vs. preference human judgments best? This can be done using linear models to confirm the results of LDA.

**Comment by sabjoslo** [comment]
What's the distinction here (i.e. are "values-based", "consequentialist" and "preference human judgements" mutually exclusive categories)? What results are you referring to, and how could a linear model confirm them?

**Comment by BabakHemmatian** [comment]
The idea that Steve had for human ratings and I was going to communicate to our collaborator tonight was to divide ten points for each comment between "consequences", "values" and "preferences". The good thing about this approach is that it can easily be turned into a categorical decision by taking the maximum, but it allows for better statistical modeling and training for the neural network if we ever decide to go down that path. Now the idea is to use multivariate GLM on topic contributions to predict these values. That would show us which topics are really contributing to the human ratings.

**Comment by sabjoslo** [comment]
Does "preferences" refer to the person's attitude towards same-sex marriage? If so, isn't that orthogonal to the C-vs-VB dimension?

**Comment by BabakHemmatian** [comment]
It is supposed to be orthogonal to that distinction. For example, part of the text might reflect the person's own sexual or romantic preferences, with no judgment cast specifically about same-sex marriage. Presumably this is picked up by LDA as well. Thing is, if we don't find that distinction helpful, we can just ignore those and base our analysis on "values" and "consequences" alone.
