### ISSUE TITLE
Test different topic contribution calculations

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#19]
Quantify the difference between the original "one-hot" topic contribution calculation, and a topic contribution calculation function that records entire probability distributions over topics.

*\*\*\*The dev module for this issue is [dev/issue19.py](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/master/dev/issue19.py).\*\*\**

**Comment by sabjoslo** [comment]
@BabakHemmatian, I've changed the topic contribution calculation to multiply the contribution of each word by the number of times it occurs in the comment being analyzed (see lines 589--599 of [this version](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/issue19/ModelEstimation.py) of ModelEstimation). I figured this was more consistent with how we want topic contributions to be calculated, but let me know if you had something else in mind.

**Comment by BabakHemmatian** [comment]
@sabjoslo, if I'm understanding you correctly (the code has changed so much that I can't be entirely sure), your version would be the correct one if per-word topics in Gensim ignore multiple occurrences of a word in a document. Have you checked for this? For example, if we give Gensim a sentence like "a man chased another man", does the tuple related to "man" appear only once in the output?

**Comment by sabjoslo** [comment]
> For example, if we give Gensim a sentence like "a man chased another man", does the tuple related to "man" appear only once in the output?

Yes. But also check out this strange thing that happened when I ran that sanity check:
```
> ldamodel=gensim.models.LdaMulticore.load("all_processed_data/RC_LDA_50_True.lda")
> doc_topics, term_topics, phis=ldamodel.get_document_topics(ldamodel.id2word.doc2bow(["a", "man", "chased", "another", "man"]), per_word_topics=True)
> phis
[(2354, [(2, 0.055739799130425587), (19, 0.94422237749761118)]),
 (23203, [(19, 1.9997420214698975)]),
 (33471, [(2, 0.99997505771110262)])]
> ldamodel.id2word[2354]
u'another'
> ldamodel.id2word[19]
u'rawhide' # WTF?
> ldamodel.id2word[23203]
u'man'
> ldamodel.id2word[33471]
u'chased
```

**Comment by BabakHemmatian** [comment]
This snippet suggests that we should multiply by the number of occurrences, as you said. Man has shown up in the phi tuples just once.
19 is not a word id, it is just another topic whose phi value for the word "another"- given the context- has passed the threshold. The other one is topic 2.
What the code I had written would do, would be to simply take the value associated with the most probable topic (in this case likely to be topic 19) and through he rest away. If I understand correctly, you wish to add the other topics to the aggregate too. Regardless, you should use term_topics instead, which is normalized and can be used as a probability estimate.

**Comment by sabjoslo** [comment]
> 19 is not a word id, it is just another topic whose phi value for the word "another"- given the context- has passed the threshold. The other one is topic 2.

You're right--I looked at the output too quickly. Thanks for being more reflective than me...

> Regardless, you should use term_topics instead, which is normalized and can be used as a probability estimate.

What do you mean by "normalized"?

I'm currently using the distribution of phi values returned by `get_document_topics` (see lines 594--598 of [this version](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/master/ModelEstimation.py) of ModelEstimation). I believe `get_term_topics` just outputs the odds of a word belonging to a given topic, which does not necessarily sum to one:
```
> ldamodel.get_term_topics("man")
[(19, 0.14223084385142357)]
```

The phi values are a scaled probability distribution--in particular, the distribution of the posterior probability of a given word belonging to a given topic, multiplied by the number of times that word occurs in the document passed as an argument. The phi distribution for a given word should sum to the number of times that word occurs in the document (and I've included an assertion in ModelEstimation that verifies this).* This is why the phi distribution for "another" (above) sums to (approximately) 1 (0.055739799130425587 + 0.94422237749761118) and the phi values for "man" sum to 2. (More info on the difference between `get_term_topics` and `get_document_topics` [here](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/topic_methods.ipynb).)

I actually think this implies that we should change the topic contribution calculation to use phi values even when the document is only one word long. What do you think?

*Actually, it doesn't sum to *exactly* the number of occurrences because gensim ignores any topic with a phi value less than 1e-8. Right now I'm just ignoring that fact, but there might be another way to deal with that (see [here](https://groups.google.com/forum/#!topic/gensim/m4eSqVqYzdo)). I've added a note to myself on the issue description to look further into this.

**Comment by BabakHemmatian** [comment]
I'm really tired right now, so I hope I'll make sense. You can't just add the phi values to the topic contribution calculation, because it's not normalized: Each word is contributing a fraction to the mix of topics that make up a document in our notion of contribution, not something like 2. The normalization in the topic contribution calculation takes care of that.
Now do we need to multiply the value by the number of times a word occurs after retrieving phi's? If I understand this correctly, and I understood what you were saying earlier correctly, we shouldn't.The calculation of phi takes care of that

**Comment by sabjoslo** [comment]
I'm not totally following you. Maybe this would be better hashed out over the phone?

**Comment by BabakHemmatian** [comment]
Sure. Text me with a time that works for you :)

**Comment by sabjoslo** [comment]
The results are in! As I mentioned, I ran the topic contribution calculations 10 times for each topic contribution function (one-hot and distribution-based). For each pair of runs, I calculated the JSD between the topic distributions. As we hoped, the JSD between runs using the same function is effectively zero. When using different functions, the distance between the distributions is about 1e-3. And the 5 top topics are identical for all 20 runs. So in short, the two functions seem to yield very similar (effectively identical?) results, and I don't think it matters which function we choose to go with.

**Comment by BabakHemmatian** [comment]
That's great news! So should I move forward with getting human ratings for the sampled comments with the topic contribution results I already have?

**Comment by sabjoslo** [comment]
I still have to calculate monthly topic contributions (#15). You also mentioned that you wanted to change the top topic criterion (although I don't see an issue open for that). Right now, `n_top_topics = 5`. How much do you think that should change by?

**Comment by BabakHemmatian** [comment]
In the version of the results I reported, the number of top topics was determined dynamically based on the overall number of topics (0.1 of `n_topics`). Uriel's suggestion was to set a threshold based on average contribution instead and look at all topics that pass that criterion (for example, all topics with a contribution averaged over the years of higher than 1/`n_topics`). 
The top 0.1 topics, therefore, aren't going to change. Some other topics may need to be added to the bundle (probably only a few). I was going to redo the sampling of the top comments with the new criteria over the weekend, so that we'll have comments to give raters.
Changing to monthly topic contributions shouldn't change the sampled top comments. My main worry is whether coherence would in fact support the choice of 50 topics. If not, the sampled comments may need to change. But I'm just swamped with urgent work and wonder when I'll be able to look at that

**Comment by sabjoslo** [comment]
> My main worry is whether coherence would in fact support the choice of 50 topics. If not, the sampled comments may need to change.

I don't think it really matters. Choosing `num_topics` isn't an exact science. Topic coherence is an estimate of an ensemble of proxies of human judgment. I don't see why actual human judgment (ours) should be worthless. It would be nice if it corroborates our intuition, but if it doesn't, it's an avenue for future exploration.

**Comment by BabakHemmatian** [comment]
That's a good point. I'll go ahead and get the sampled comments for the broader definition of top topic then. I'll send it to our raters and hopefully we'll get their ratings really soon.

**Comment by sabjoslo** [comment]
Thanks! Which topic contribution function do you think we should use for the final analysis?

**Comment by BabakHemmatian** [comment]
The use of yours can be justified more easily
