### ISSUE TITLE
Calculate topic coherence metrics for topic models with varying num_topics

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#22]
To address the difference in "quality" between LDA models with different numbers of topics, calculate the [topic coherence](https://radimrehurek.com/gensim/models/coherencemodel.html) of models with 25, 50, 75 and 100 topics (example [here](https://groups.google.com/forum/#!topic/gensim/NyBJeNVDeSQ)).

**Comment by sabjoslo** [comment]
Did you calculate these? What were the results?

**Comment by BabakHemmatian** [comment]
Unfortunately not very helpful. The fewer the topics, the better the umass coherence. Even down to 2 topics. The extrinsic measures wouldn't be easy to calculate given the dataset we have and our goals either. We would need an external corpus of same-sex-marriage-related discussions. Thing is, the coherence value for 50 topics was quite acceptable. So I think we should go with that.
