### ISSUE TITLE
Break up Utils

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#25]
I think it would be nice (i.e. more usable and readable) to break up Utils into a few separate modules, e.g. a Parser, an LDATrainer, an NNTrainer, a TopicContributionCalculator, etc. @BabakHemmatian, what do you think? I'd be more than happy to take this on if you think it's a good idea.

**Edit:** As of 1716955, this is done **except** for one outstanding thing that's still bothering me: Top topics are still calculated directly from `Reddit_LDA_Analysis`. I think this should be incorporated into the `LDAModel` class as a class method (and the `report` object incorporated as a `LDAModel` class attribute).

Also, I'd like to collect all filenames into a set of configurable class attributes, rather than having them be hard-coded in the bodies of various class methods.

**Comment by BabakHemmatian** [comment]
I think that's a good idea. When I started writing in Utils, it wasn't thousand of lines long. It's kind of getting out of hand. Separating modules would make updating code easier too. I think we should still keep the functions that are shared between NN and LDA (and just take NN as an argument) in Utils. Please let me know if you would like help with any of these tweaks.

**Comment by sabjoslo** [comment]
@BabakHemmatian, I noticed that much of the code in `NN_clean` and `LDA_clean` was virtually identical, so in 0cd2f0d I copied the bulk of it to a function `Parser._clean` called by both of them. The only difference I noticed was in lines 151 and 191 of [the previous version of Utils](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/c99f76f562755ecf4b6663c905cb422a3c549de8/Utils.py):

```
# NN_clean
151: for word in stop_free.split():
#
# LDA_clean
191: for word in stop_free.lower().split():
```

Is there a reason the text passed to `NN_clean` wasn't converted to lowercase, and should I go back and change that?

**Comment by sabjoslo** [comment]
OK, this is mostly done (see edit on issue description). A couple questions for you:
- See lines 279--282 of [ModelEstimation](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/17169558d88c60c145599f0db47cf1436b0237f1/ModelEstimation.py). As we discussed on #27, `indices` is a list of the cumulative comment counts per month, so the `assert` I commented out didn't make much sense to me. Is this change consistent with what you intended here?
- I got rid of two functions that were in the original `Utils`: `info()` and `is_number()`. `is_number()` was being called on [lines 121--123](https://github.com/BabakHemmatian/Gay_Marriage_Corpus_Study/blob/17169558d88c60c145599f0db47cf1436b0237f1/ModelEstimation.py), and I replaced these calls with `.isdigit()`. **This won't work if any of the arguments are floats.** If that's the case, let me know and I'll reinstate `is_number()`! I'm also happy to reinstate `info()` if you think it'd be helpful!

**Comment by BabakHemmatian** [comment]
Thanks for doing all this restructuring and sorry that the code was so messy to begin with. I hope this didn't take too much of your time.

- `indices` is not supposed to be the cumulative comment count for NN. See line 127 of `ModelEstimation.py`. It is the set of comment indices for which we have a full record of human judgments. So `len(indices)` is equal to the number of rated comments and if the set function is doing what it should, the sum of training, development and test sets should be equal to its value.

- The info function was just meant to make sure during development that the multi-processing and threaded versions of functions were really working they way they should (assigning works to an appropriate number of workers). If there's no further use for it developing similar functions, feel free to discard it. As for is_number(), I guess the collaborator ratings are expected to be integers, so isdigit() should work fine.

**Comment by sabjoslo** [comment]
> `indices` is not supposed to be the cumulative comment count for NN. See line 127 of `ModelEstimation.py`.

This line is only executed if `regression==True` though, right? If `regression==False`, will `indices` still be a list of the cumulative comment counts? If so and if that's unintended, I can change it to equal `range(indices[-1])`.

**Comment by BabakHemmatian** [comment]
Yes, if `regression==False`, we'll be doing language modeling and `indices` should stand for the cumulative count, meaning the assertion should use `range(indices[-1])` as you suggested. Thanks for catching that bug!
