### ISSUE TITLE
How can we respond to uneven amounts of data across media sources and years?

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#5]
I just put two DataFrames in the repo that should give us a sense of how our data is distributed across platforms and years. You can open them like this:
```
import pandas as pd
pd.read_pickle('n_posts.pandas')
```
n_posts.pandas shows the number of posts we have grouped by source and year, and n_comments.pandas shows the number of comments we have grouped by source and year.

As I wrote in my email, the only caveat to keep in mind is that the program crashed while collecting data for 2015 posts from Fox News--because there was so much of it. So while looking at these numbers, assume that we could also have tens of thousands of comments from Fox News in both 2015 and 2016.

One thing I noticed is that we have no data from 2008, and very little from 2009.

So I have two questions (well, two categories of questions...):
1. I haven't really studied to what extent there's an unequal distribution if we just group by source partisanship (in other words, it's totally possible that, for example, the thousands of FoxNews comments are balanced out by thousands of nytimes comments). Do you notice anything about these numbers that we should (or shouldn't) correct for? What else should I be asking about the distribution of this data, other than how it groups by source/year?

2. Given the potential for an uneven distribution across sources and years, how and do you think we should re-weight or re-sample our data? Some vaguely-formulated proposals I have are to:
- Sample randomly and evenly across platforms (this would not account for the lack of data from '08).
- Almost equivalently, re-weight observations so comments from sources (and years?) with less data are more heavily weighted.
- If either of these approaches makes it so we don't have enough data, or are heavily weighting ridiculously small amounts of data, we could also look into retrieving data from additional news sources.
---------------
**Edit:** Here is the infographic that inspired my initial choice of platform: http://wilkins.law.harvard.edu/projects/2017-08_mediacloud/Graphics/Fig7_11.pdf. It's taken from this paper: Faris, Robert and Roberts, Hal and Etling, Bruce and Bourassa, Nikki and Zuckerman, Ethan and Benkler, Yochai, Partisanship, Propaganda, and Disinformation: Online Media and the 2016 U.S. Presidential Election (August 2017). Berkman Klein Center Research Publication 2017-6. Available at SSRN. Quoting from the paper, "[t]he size of each media source node is in proportion to the number of other media sources that link to that source at least once" and "[t]he colors on the map reflect the partisan pattern of attention to the media sources based on the sharing
behavior of Twitter users who have clear partisan allegiances".

**Comment by BabakHemmatian** [comment]
Thanks for the data and the DataFrames! I assume that DataFrames provide much more information that we will be using than year and outlet. I had already included code that counts documents by year and source in the last version of the parser that I uploaded to GitHub. I just used my own code to get this distribution:

('2009FoxNews', 412), ('2009HuffPost', 347), ('2009nationalreview', 10), ('2009nytimes', 839), ('2010FoxNews', 9696)
('2010HuffPost', 498), ('2010nationalreview', 21), ('2010nytimes', 1105), ('2010usatoday', 83), ('2010washingtonpost', 318), ('2010wsj', 225)
 ('2011FoxNews', 21558), ('2011HuffPost', 2124), ('2011TheHill', 24), ('2011nationalreview', 84), ('2011nytimes', 2387), ('2011realclearpolitics', 1), ('2011usatoday', 141), ('2011washingtonpost', 1116), ('2011wsj', 269)
('2012FoxNews', 13268), ('2012HuffPost', 20746), ('2012TheHill', 405), ('2012nationalreview', 98), ('2012nytimes', 1873), ('2012realclearpolitics', 40), ('2012usatoday', 241), ('2012washingtonpost', 1686), ('2012wsj', 301)
('2013FoxNews', 14934), ('2013HuffPost', 11024), ('2013TheHill', 231),('2013nationalreview', 548), ('2013nytimes', 4965), ('2013realclearpolitics', 28), ('2013usatoday', 862), ('2013washingtonpost', 1753), ('2013wsj', 401)
('2014FoxNews',61175), ('2014HuffPost', 11741), ('2014TheHill', 1719), ('2014nationalreview', 537), ('2014nytimes', 10994), ('2014realclearpolitics', 6), ('2014usatoday', 6702), ('2014washingtonpost', 4000), ('2014wsj', 233)
('2015FoxNews', 20932), ('2015HuffPost', 13068), ('2015TheHill', 44590), ('2015nationalreview', 1278), ('2015nytimes', 55998), ('2015realclearpolitics', 369), ('2015usatoday', 18608), ('2015washingtonpost', 14956), ('2015wsj', 4597)
('2016FoxNews', 8), ('2016HuffPost', 5623), ('2016TheHill', 10451), ('2016nationalreview', 2127), ('2016nytimes', 9155), ('2016usatoday', 1366), ('2016washingtonpost', 4994), ('2016wsj', 671)
('2017FoxNews', 2), ('2017HuffPost', 1), ('2017TheHill', 5), ('2017nationalreview', 1), ('2017nytimes', 57), ('2017usatoday', 5), ('2017wsj', 2)])

When I tell my friends that the right is OBSESSED with homosexuality, they don't believe me. With only a few exceptions, FoxNews alone has way more relevant documents than the other outlets combined. Some outlets have hardly any for certain years (e.g. realclearpolitics). I'm not sure if we need to do anything about that though. Weighting documents differentially can mess with the topics that come out of LDA in somewhat unpredictable ways and would be difficult to justify in a paper. We could sample randomly and evenly across platforms. But I wonder if we really want that. That a certain subpopulation discusses this issue more often than others is an interesting fact about our data. We want to get a good representation of the trends that show up in people's discussions of the issue, and that includes both the volume and the topics and frames of discussion. If we don't like the topics that come out, we can always just do separate analyses on different sets of outlets. Combined, the liberal and centrist outlets each have enough information to separately support a good LDA model.

That said, I think we should change those outlets that do not have much relevant data at all. If a source is not really contributing much to our data, why are we including it? realclearpolitics seems to have the least amount of data.

I don't think having no data from 2008 would be a big problem. We still have data from quite a few years, so we can get a good trend if it exists. This is just a feature of our corpus that will be mentioned in the paper. Plus we have that period covered with Reddit.

By the way, did you contact Uriel to have an account set up on the server or should I contact him on your behalf?

**Comment by sabjoslo** [comment]
> I'm not sure if we need to do anything about that though. Weighting documents differentially can mess with the topics that come out of LDA in somewhat unpredictable ways and would be difficult to justify in a paper. We could sample randomly and evenly across platforms. But I wonder if we really want that. That a certain subpopulation discusses this issue more often than others is an interesting fact about our data. We want to get a good representation of the trends that show up in people's discussions of the issue, and that includes both the volume and the topics and frames of discussion.

I don't know to what extent the fact that Fox News has three times as many followers as the Washington Post is telling of something fundamental about the national discourse around gay marriage. That being said, you raise a good point that makes me realize that there is no underlying, "fundamental" distribution of discourse which is being only approximated by our data; visible comments on the issue in a sense define that distribution.

I guess what matters then is the degree of generalizability of our data. Are enough people experiencing American politics through Facebook that it makes sense to extrapolate to trends about "people's discussions of the issue"? Failing that, are these distributions representative of whatever "people's discussions" are?

Finally. if we’re not trying to somewhat correct for partisan bias, why are we sampling outlets evenly across the partisan spectrum?

> That said, I think we should change those outlets that do not have much relevant data at all. If a source is not really contributing much to our data, why are we including it?

Fair. I’ve updated the description of this issue to include a link to the infographic that inspired my initial choice of platforms. Do you have any suggestions of alternative platforms to look to?

> Plus we have that period covered with Reddit.

I haven’t gotten around to getting Reddit data yet. Are you thinking about **combining** them in this initial analysis, or analyzing them separately (e.g. work with Facebook now, and Reddit later)?

> By the way, did you contact Uriel to have an account set up on the server or should I contact him on your behalf?

Just sent him an email.

**Comment by BabakHemmatian** [comment]
> Are enough people experiencing American politics through Facebook that it makes sense to extrapolate to trends about "people's discussions of the issue"? Failing that, are these distributions representative of whatever "people's discussions" are?

Is the sample biased? Yes, it is. But so is any sample based on social media and there is evidence that, among our options, Facebook is actually quite representative of the population and widely used. [This study](http://www.niemanlab.org/2016/05/pew-report-44-percent-of-u-s-adults-get-news-on-facebook/), for example, shows that about half of all Americans receive their daily news from Facebook and even though certain types of people are more likely to comment on things, it stands to reason that Facebook would be one of the best places to gain a good sample of the general discussion about an issue.

> Finally. if we’re not trying to somewhat correct for partisan bias, why are we sampling outlets evenly across the partisan spectrum?

We are trying to ensure that all political views are represented in the data. Having equal amounts of data from the various sources is not required. We should actually take advantage of all the data that we have. One thing that my preliminary LDA showed is that even with as few as 400 comments, we can have some really nice topics. So I think we can easily even do separate LDAs for different parts of the spectrum. 

> Fair. I’ve updated the description of this issue to include a link to the infographic that inspired my initial choice of platforms. Do you have any suggestions of alternative platforms to look to?

Based on the network map in the paper you used, I suggest adding some outlets and removing others to make the list more representative of the whole spectrum. CNN and Politico are categorized as liberal (they seem pretty centrist to me, but I guess the categorization tells us more about what the average American mindset looks like) and seem to have an outsized presence. We could add them to get more liberal data. They call Breitbart "the nexus of conservative media". I feel it needs to be included. We could balance it out by adding more extreme leftist outlets. Jacobin or The Nation come to mind, but they don't have as big a following as Breitbart, so maybe NPR? On the right, Daily Mail and Washington Observer look like more mainstream alternatives to RealClearPolitics. These are all suggestions. I defer to your judgment on the final list.

> I haven’t gotten around to getting Reddit data yet. Are you thinking about combining them in this initial analysis, or analyzing them separately (e.g. work with Facebook now, and Reddit later)?

I have the code set up such that we determine the value of a "database" variable and based on that the analysis is done on either Facebook, or Reddit. I think this is the best approach. We would want separate analyses from different platforms to show that our results converge regardless of the context.

**Comment by sabjoslo** [comment]
See my most recent commit (above) for new list of news outlets.

**Comment by BabakHemmatian** [comment]
I think it looks great! We have a well-justified methodology for categorizing them and we have a range of political leanings among the most popular outlets on the most popular social media. My only tentative suggestion is to consider the unbiased score range to be a bit wider. Other than that, I say let's move forward! I have the code for lda all ready and can run the analysis as soon as I get the data :)
