### ISSUE TITLE
Diverse samples

### ISSUE THREAD

**Issue by BabakHemmatian** [BabakHemmatian/Gay_Marriage_Corpus_Study#7]
- Random comment samples
- Probabilities of all top topics for each sample
- Different categories of top topics based on the values/consequences distinction

**Comment by sabjoslo** [comment]
@BabakHemmatian, is this still relevant?

**Comment by BabakHemmatian** [comment]
@sabjoslo 

- Probably not. Steve pointed out that given how variable what people talk about can be, Just randomly sampling from the comments might not give us clearly value-based or consequence-based comments and it would be best to have SOME basis for choosing the comments. But it depends on how our top topic comment samples turn out. 
- It would still be helpful to get probabilities of all top topics for each sample. It would tell us how entangled our various topics are
- Whether the last one is relevant depends on how neatly our top topics can be classified as based on values/consequences
